apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: amqp-client
  name: amqp-client
spec:
  template:
    metadata:
      labels:
        app: amqp-client
    spec:
      containers:
      - image: ssorj/quiver
        imagePullPolicy: IfNotPresent
        name: amqp
        args: ["quiver", "-d", "30s", "amqp://${AMQP_SERVER}/q0"]
        ports:
        - containerPort: 5201
          name: port5201
          protocol: TCP
#        resources:
#          requests:
#            cpu: "1.0"
      restartPolicy: "Never"
