apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: http-client-wrk
  name: http-client-wrk
spec:
  template:
    metadata:
      labels:
        app: http-client-wrk
    spec:
      containers:
      - image: quay.io/fgiorgetti/wrk
        imagePullPolicy: IfNotPresent
        name: http
        args: ["wrk", "-d", "30s", "http://${HTTP_SERVER}:${HTTP_PORT}"]
        #args: ["wrk", "-d", "30s", "-c", "10", "http://${HTTP_SERVER}:${HTTP_PORT}"]
#        resources:
#          requests:
#            cpu: "1.0"
      restartPolicy: "Never"
