apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: iperf-client
  name: iperf-client
spec:
  template:
    metadata:
      labels:
        app: iperf-client
    spec:
      containers:
      - image: quay.io/skupper/iperf3
        imagePullPolicy: IfNotPresent
        name: iperf3
        #args: ["-c", "${IPERF_SERVER}", "-t", "30", '-f', 'g']
        args: ["-c", "${IPERF_SERVER}", "-t", "30", "-P", "10", "-f", "g"]
        ports:
        - containerPort: 5201
          name: port5201
          protocol: TCP
#        resources:
#          requests:
#            cpu: "1.0"
      restartPolicy: "Never"
